### ISSUE TITLE
command RNIDE.diagnose not found

### ISSUE THREAD

**Issue by ziademadmohammed** [software-mansion/radon-ide#620]
**Description**
after installing the extension the UI to start using it doesn't appear. the docs recommend using the diagnose command but i get this error

https://github.com/user-attachments/assets/0eb87fd0-1f0a-41e3-86f4-bf1c070f94a7

**Environment**

Expo project (SDK 51)
latest version of vscode 1.94
latest version of extension .19

**Comment by ziademadmohammed** [comment]
upon further debugging. found that the extension is throwing an error on startup 
```
2024-10-15 00:51:41.337 [info] ExtensionService#_doActivateExtension swmansion.react-native-ide, startup: true, activationEvent: 'workspaceContains:node_modules/react-native'
2024-10-15 00:51:41.377 [error] Activating extension swmansion.react-native-ide failed due to an error:
2024-10-15 00:51:41.377 [error] Error: Unsupported platform
    at /home/ziade/.var/app/com.visualstudio.code/data/vscode/extensions/swmansion.react-native-ide-0.0.19/dist/extension.js:103:32438
    at Object.<anonymous> (/home/ziade/.var/app/com.visualstudio.code/data/vscode/extensions/swmansion.react-native-ide-0.0.19/dist/extension.js:103:32474)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at Function.c._load (node:electron/js2c/node_init:2:13801)
    at Function.e._load (file:///app/extra/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10870)
    at Function.t._load (file:///app/extra/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22422)
    at Function.i._load (file:///app/extra/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at hB.xb (file:///app/extra/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:23767)
    at async Promise.all (index 0)
```

**Comment by ziademadmohammed** [comment]
upon checking the extension code. i found out it only supports windows and macos. this is not refrenced in the installation section in the docs. also the [warning supposed](https://github.com/software-mansion/radon-ide/blob/main/packages/vscode-extension/src/extension.ts#L66) to tell that other platforms aren't supported didn't show up for me
