### ISSUE TITLE
App crashes when changing font size 

### ISSUE THREAD

**Issue by maciekstosio** [software-mansion/radon-ide#781]
**Description**
App crashes when changing the font size. 

**Environment**

- Radon IDE 0.24-beta
- React Native 0.73.4

**Steps to reproduce**

- Open `test-apps/react-native-73` with Radon IDE
- Change font size 

<video src="https://github.com/user-attachments/assets/a05dfaac-7dd5-4d3e-8e84-c0eb48b03d5b" />

**Comment by maciekstosio** [comment]
Continues in 1.0-rc.2 
```
--------- beginning of main
11-29 21:12:09.354  6541  6541 I m.rnboilerplate: Late-enabling -Xcheck:jni
11-29 21:12:09.402  6541  6541 I m.rnboilerplate: Using CollectorTypeCC GC.
11-29 21:12:09.452  6541  6541 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10190; state: ENABLED
11-29 21:12:09.452  6541  6541 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10190; state: ENABLED
11-29 21:12:09.456  6541  6541 W ziparchive: Unable to open '/data/app/~~KoKzZ3C-_KF9HyCU8otYnw==/com.rnboilerplate-zezloZRu8trS3mDrDmJdcQ==/base.dm': No such file or directory
11-29 21:12:09.456  6541  6541 W ziparchive: Unable to open '/data/app/~~KoKzZ3C-_KF9HyCU8otYnw==/com.rnboilerplate-zezloZRu8trS3mDrDmJdcQ==/base.dm': No such file or directory
11-29 21:12:09.560  6541  6541 D nativeloader: Configuring clns-6 for other apk /data/app/~~KoKzZ3C-_KF9HyCU8otYnw==/com.rnboilerplate-zezloZRu8trS3mDrDmJdcQ==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~KoKzZ3C-_KF9HyCU8otYnw==/com.rnboilerplate-zezloZRu8trS3mDrDmJdcQ==/lib/arm64:/data/app/~~KoKzZ3C-_KF9HyCU8otYnw==/com.rnboilerplate-zezloZRu8trS3mDrDmJdcQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.rnboilerplate
11-29 21:12:09.573  6541  6541 V GraphicsEnvironment: Currently set values for:
11-29 21:12:09.573  6541  6541 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[]
11-29 21:12:09.573  6541  6541 V GraphicsEnvironment:   angle_gl_driver_selection_values=[]
11-29 21:12:09.573  6541  6541 V GraphicsEnvironment: ANGLE GameManagerService for com.rnboilerplate: false
11-29 21:12:09.573  6541  6541 V GraphicsEnvironment: com.rnboilerplate is not listed in per-application setting
11-29 21:12:09.573  6541  6541 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
11-29 21:12:09.580  6541  6541 V SoLoader: Init System Loader delegate
11-29 21:12:09.629  6541  6569 D TrafficStats: tagSocket(81) with statsTag=0xffffffff, statsUid=-1
11-29 21:12:09.631  6541  6570 D TrafficStats: tagSocket(82) with statsTag=0xffffffff, statsUid=-1
11-29 21:12:09.643  6541  6541 W m.rnboilerplate: Accessing hidden field Landroid/view/View;->mKeyedTags:Landroid/util/SparseArray; (unsupported, reflection, allowed)
11-29 21:12:09.643  6541  6541 W m.rnboilerplate: Accessing hidden field Landroid/view/View;->mListenerInfo:Landroid/view/View$ListenerInfo; (unsupported, reflection, allowed)
11-29 21:12:09.643  6541  6541 W m.rnboilerplate: Accessing hidden field Landroid/view/View$ListenerInfo;->mOnClickListener:Landroid/view/View$OnClickListener; (unsupported, reflection, allowed)
11-29 21:12:09.645  6541  6541 I flipper : flipper: FlipperClient::addPlugin Inspector
11-29 21:12:09.647  6541  6541 I flipper : flipper: FlipperClient::addPlugin Databases
11-29 21:12:09.647  6541  6541 I flipper : flipper: FlipperClient::addPlugin Preferences
11-29 21:12:09.647  6541  6541 I flipper : flipper: FlipperClient::addPlugin CrashReporter
11-29 21:12:09.648  6541  6541 I flipper : flipper: FlipperClient::addPlugin Network
11-29 21:12:09.658  6541  6567 W System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
11-29 21:12:09.658  6541  6567 W System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
11-29 21:12:09.658  6541  6567 W System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
11-29 21:12:09.659  6541  6581 D libEGL  : loaded /vendor/lib64/egl/libEGL_emulation.so
11-29 21:12:09.659  6541  6581 D libEGL  : loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
11-29 21:12:09.661  6541  6581 D libEGL  : loaded /vendor/lib64/egl/libGLESv2_emulation.so
11-29 21:12:09.669  6541  6582 D TrafficStats: tagSocket(83) with statsTag=0x90000, statsUid=-1
11-29 21:12:09.670  6541  6541 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
11-29 21:12:09.688  6541  6585 D TrafficStats: tagSocket(94) with statsTag=0xffffffff, statsUid=-1
11-29 21:12:09.693  6541  6541 W m.rnboilerplate: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
11-29 21:12:09.693  6541  6541 W m.rnboilerplate: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
11-29 21:12:09.703  6541  6541 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10190; state: DISABLED
11-29 21:12:09.704  6541  6541 W OpenGLRenderer: Unknown dataspace 0
11-29 21:12:09.719  6541  6541 W unknown:ReactNative: Packager connection already open, nooping.
11-29 21:12:09.789  6541  6579 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
11-29 21:12:09.792  6541  6579 W OpenGLRenderer: Failed to initialize 101010-2 format, error = EGL_SUCCESS
11-29 21:12:09.802  6541  6579 I Gralloc4: mapper 4.x is not supported
11-29 21:12:09.806  6541  6579 E OpenGLRenderer: Unable to match the desired swap behavior.
11-29 21:12:09.844  6541  6541 D CompatibilityChangeReporter: Compat change id reported: 210923482; UID 10190; state: ENABLED
11-29 21:12:09.870  6541  6579 E OpenGLRenderer: Unable to match the desired swap behavior.
11-29 21:12:10.211  6541  6541 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@4e34704
11-29 21:12:10.240  6541  6541 W unknown:ReactNative: Packager connection already open, nooping.
11-29 21:12:10.255  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.traceupdateoverlay.TraceUpdateOverlayManager
11-29 21:12:10.259  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
11-29 21:12:10.261  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
11-29 21:12:10.266  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
11-29 21:12:10.269  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
11-29 21:12:10.270  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
11-29 21:12:10.271  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
11-29 21:12:10.272  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
11-29 21:12:10.274  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
11-29 21:12:10.277  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
11-29 21:12:10.277  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
11-29 21:12:10.280  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
11-29 21:12:10.280  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
11-29 21:12:10.282  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
11-29 21:12:10.284  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
11-29 21:12:10.286  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
11-29 21:12:10.286  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
11-29 21:12:10.286  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextShadowNode
11-29 21:12:10.287  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
11-29 21:12:10.292  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
11-29 21:12:10.293  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
11-29 21:12:10.294  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
11-29 21:12:10.295  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
11-29 21:12:10.297  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
11-29 21:12:10.297  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
11-29 21:12:10.298  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.unimplementedview.ReactUnimplementedViewManager
11-29 21:12:10.298  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class org.reactnative.maskedview.RNCMaskedViewManager
11-29 21:12:10.299  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.gesturehandler.react.RNGestureHandlerRootViewManager
11-29 21:12:10.300  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.gesturehandler.react.RNGestureHandlerButtonViewManager
11-29 21:12:10.305  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.th3rdwave.safeareacontext.SafeAreaProviderManager
11-29 21:12:10.306  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.th3rdwave.safeareacontext.SafeAreaViewManager
11-29 21:12:10.306  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.th3rdwave.safeareacontext.SafeAreaViewShadowNode
11-29 21:12:10.307  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreenContainerViewManager
11-29 21:12:10.308  6541  6594 E unknown:UIManagerModuleConstantsHelper: Direct event name for 'RNSScreen' doesn't correspond to the naming convention, expected 'topEventName'->'onEventName', got 'topHeaderBackButtonClickedEvent'->'onHeaderBackButtonClicked'
11-29 21:12:10.308  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreenViewManager
11-29 21:12:10.309  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreenStackViewManager
11-29 21:12:10.309  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreenStackHeaderConfigViewManager
11-29 21:12:10.310  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreenStackHeaderSubviewManager
11-29 21:12:10.310  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.SearchBarManager
11-29 21:12:10.313  6541  6594 W m.rnboilerplate: Accessing hidden field Ljava/lang/reflect/Field;->accessFlags:I (unsupported, reflection, allowed)
11-29 21:12:10.333  6541  6594 I flipper : flipper: FlipperClient::addPlugin Fresco
11-29 21:12:10.460  6541  6594 I WebViewFactory: Loading com.google.android.webview version 113.0.5672.136 (code 567263634)
11-29 21:12:10.462  6541  6594 W ziparchive: Unable to open '/data/app/~~wSPQstJfE8F1t9tIqZmoRw==/com.google.android.trichromelibrary_567263634-_xoGCjD7XabDuQ4Ql4-XoA==/TrichromeLibrary.dm': No such file or directory
11-29 21:12:10.462  6541  6594 W ziparchive: Unable to open '/data/app/~~wSPQstJfE8F1t9tIqZmoRw==/com.google.android.trichromelibrary_567263634-_xoGCjD7XabDuQ4Ql4-XoA==/TrichromeLibrary.dm': No such file or directory
11-29 21:12:10.462  6541  6594 W m.rnboilerplate: Entry not found
11-29 21:12:10.464  6541  6594 D nativeloader: Configuring clns-7 for other apk /data/app/~~wSPQstJfE8F1t9tIqZmoRw==/com.google.android.trichromelibrary_567263634-_xoGCjD7XabDuQ4Ql4-XoA==/TrichromeLibrary.apk. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~P7Ch2cwPvLz5pgo7ZoGx6g==/com.google.android.webview-ptg1yXn3oX3JtftB0ekpiw==/lib/arm64:/data/app/~~P7Ch2cwPvLz5pgo7ZoGx6g==/com.google.android.webview-ptg1yXn3oX3JtftB0ekpiw==/WebViewGoogle.apk!/lib/arm64-v8a:/data/app/~~wSPQstJfE8F1t9tIqZmoRw==/com.google.android.trichromelibrary_567263634-_xoGCjD7XabDuQ4Ql4-XoA==/TrichromeLibrary.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
11-29 21:12:10.466  6541  6594 D nativeloader: Configuring clns-8 for other apk /data/app/~~P7Ch2cwPvLz5pgo7ZoGx6g==/com.google.android.webview-ptg1yXn3oX3JtftB0ekpiw==/WebViewGoogle.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~P7Ch2cwPvLz5pgo7ZoGx6g==/com.google.android.webview-ptg1yXn3oX3JtftB0ekpiw==/lib/arm64:/data/app/~~P7Ch2cwPvLz5pgo7ZoGx6g==/com.google.android.webview-ptg1yXn3oX3JtftB0ekpiw==/WebViewGoogle.apk!/lib/arm64-v8a:/data/app/~~wSPQstJfE8F1t9tIqZmoRw==/com.google.android.trichromelibrary_567263634-_xoGCjD7XabDuQ4Ql4-XoA==/TrichromeLibrary.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
11-29 21:12:10.477  6541  6594 W m.rnboilerplate: Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (unsupported, reflection, allowed)
11-29 21:12:10.477  6541  6594 W m.rnboilerplate: Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (unsupported, reflection, allowed)
11-29 21:12:10.477  6541  6594 W m.rnboilerplate: Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (unsupported, reflection, allowed)
11-29 21:12:10.477  6541  6594 W m.rnboilerplate: Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (unsupported, reflection, allowed)
11-29 21:12:10.477  6541  6594 W m.rnboilerplate: Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (unsupported, reflection, allowed)
11-29 21:12:10.488  6541  6594 I cr_WVCFactoryProvider: Loaded version=113.0.5672.136 minSdkVersion=29 isBundle=false multiprocess=true packageId=2
11-29 21:12:10.496  6541  6602 I cr_VariationsUtils: Failed reading seed file "/data/user/0/com.rnboilerplate/app_webview/variations_seed_new"
11-29 21:12:10.496  6541  6602 I cr_VariationsUtils: Failed reading seed file "/data/user/0/com.rnboilerplate/app_webview/variations_seed"
11-29 21:12:10.497  6541  6594 I cr_LibraryLoader: Successfully loaded native library
11-29 21:12:10.498  6541  6594 I cr_CachingUmaRecorder: Flushed 8 samples from 8 histograms.
11-29 21:12:10.520  6541  6605 D TrafficStats: tagSocket(128) with statsTag=0xffffffff, statsUid=-1
11-29 21:12:10.522  6541  6593 I ReactNativeJS: '__RNIDE_INTERNAL', 'radon-ide runtime loaded'
11-29 21:12:10.594  6541  6593 I MMKV    : Loading C++ library...
11-29 21:12:10.596  6541  6593 I MMKV    : Installing MMKV JSI Bindings for MMKV root directory: /data/user/0/com.rnboilerplate/files/mmkv
11-29 21:12:10.596  6541  6593 I MMKV    : Successfully installed MMKV JSI Bindings!
11-29 21:12:10.596  6541  6593 I RNMMKV  : Creating MMKV instance "mmkv.default"... (Path: , Encrypted: 0)
11-29 21:12:10.601  6541  6606 D TrafficStats: tagSocket(131) with statsTag=0xffffffff, statsUid=-1
11-29 21:12:10.604  6541  6593 I ReactNativeJS: 'Running "RNBoilerplate" with {"rootTag":11}', 'http://10.0.2.2:49458/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.rnboilerplate&modulesOnly=false&runModule=true', 37175, 41
11-29 21:12:10.758  6541  6594 D CompatibilityChangeReporter: Compat change id reported: 289878283; UID 10190; state: ENABLED
11-29 21:12:10.780  6541  6593 E unknown:UIManagerModuleConstantsHelper: Direct event name for 'RNSScreen' doesn't correspond to the naming convention, expected 'topEventName'->'onEventName', got 'topHeaderBackButtonClickedEvent'->'onHeaderBackButtonClicked'
11-29 21:12:10.787  6541  6594 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreensShadowNode
11-29 21:12:10.898  6541  6541 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10190; state: ENABLED
11-29 21:12:10.898  6541  6541 W m.rnboilerplate: Accessing hidden field Landroid/widget/ScrollView;->mScroller:Landroid/widget/OverScroller; (unsupported, reflection, allowed)
11-29 21:12:10.935  6541  6541 I ReactNative: [GESTURE HANDLER] Initialize gesture handler for root view com.facebook.react.ReactRootView{13e6979 V.E...... ......ID 0,0-1080,2274 #b}
11-29 21:12:11.681  6541  6624 D TrafficStats: tagSocket(135) with statsTag=0x90000, statsUid=-1
11-29 21:12:12.685  6541  6579 D EGL_emulation: app_time_stats: avg=101.84ms min=2.33ms max=1189.10ms count=26
11-29 21:12:13.687  6541  6626 D TrafficStats: tagSocket(137) with statsTag=0x90000, statsUid=-1
11-29 21:12:15.697  6541  6628 D TrafficStats: tagSocket(137) with statsTag=0x90000, statsUid=-1
11-29 21:12:17.704  6541  6630 D TrafficStats: tagSocket(137) with statsTag=0x90000, statsUid=-1
11-29 21:12:19.711  6541  6632 D TrafficStats: tagSocket(137) with statsTag=0x90000, statsUid=-1
11-29 21:12:21.722  6541  6634 D TrafficStats: tagSocket(5) with statsTag=0x90000, statsUid=-1
11-29 21:12:22.692  6541  6541 E unknown:ReactNative: Tried to remove non-existent frame callback
11-29 21:12:22.692  6541  6541 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@b5a5640
11-29 21:12:22.719  6541  6594 W unknown:ReactNative: StatusBarModule: Ignored status bar change, current activity is null.
11-29 21:12:22.720  6541  6594 W unknown:ReactNative: StatusBarModule: Ignored status bar change, current activity is null.
11-29 21:12:22.830  6541  6541 D AndroidRuntime: Shutting down VM
--------- beginning of crash
11-29 21:12:22.832  6541  6541 E AndroidRuntime: FATAL EXCEPTION: main
11-29 21:12:22.832  6541  6541 E AndroidRuntime: Process: com.rnboilerplate, PID: 6541
11-29 21:12:22.832  6541  6541 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rnboilerplate/com.rnboilerplate.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5946)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5842)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:76)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8177)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at androidx.fragment.app.Fragment.instantiate(Fragment.java:631)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:362)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8595)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8573)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	... 15 more
11-29 21:12:22.832  6541  6541 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	... 29 more
11-29 21:12:22.832  6541  6541 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Screen fragments should never be restored. Follow instructions from https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067 to properly configure your main activity.
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	at com.swmansion.rnscreens.ScreenFragment.<init>(ScreenFragment.kt:57)
11-29 21:12:22.832  6541  6541 E AndroidRuntime: 	... 32 more
11-29 21:12:23.743  6541  6701 D TrafficStats: tagSocket(5) with statsTag=0x90000, statsUid=-1
11-29 21:12:25.756  6541  6711 D TrafficStats: tagSocket(5) with statsTag=0x90000, statsUid=-1
```
