### ISSUE TITLE
Expo-51 app crashes after start

### ISSUE THREAD

**Issue by p-malecki** [software-mansion/radon-ide#797]
**Description**
The Expo-51 app crashes on initial launch on Android devices. After crash lower button group jumps in strange way.

https://github.com/user-attachments/assets/a8e5781f-b113-4a6d-919d-c3925293aa08

**Environment**
- Radon: v1.0.0.rc1
- Test app: expo-51
- Devices: pixel 7, pixel 8

**Logs:**
```2024-11-29 17:33:00.727 [info] App ready
2024-11-29 17:33:00.729 [info] App and preview ready, moving on...
2024-11-29 17:33:01.765 [info] Connected to debugger, moving on...
2024-11-29 17:33:01.766 [info] App launched in 8.84 sec.
2024-11-29 17:33:01.766 [info] Device session started
2024-11-29 17:33:01.839 [warning] CDP message error received {"code":-32601,"message":"FuseboxClient.setClientMetadata wasn't found"}
2024-11-29 17:33:01.909 [info] Metro {"buildID":"8","bundleDetails":{"bundleType":"map","customResolverOptions":{},"customTransformOptions":{"engine":"hermes","bytecode":"true","routerRoot":"app"},"dev":true,"entryFile":"/Users/pawel/Documents/GitHub/radon-ide/test-apps/expo-51/node_modules/expo-router/entry.js","minify":false,"platform":"android"},"isPrefetch":false,"type":"bundle_build_started"}
2024-11-29 17:33:02.324 [info] Metro {"buildID":"8","type":"bundle_build_done"}
2024-11-29 17:33:02.326 [warning] CDP message error received {"code":-32601,"message":"Debugger.setAsyncCallStackDepth wasn't found"}
2024-11-29 17:33:02.329 [warning] CDP message error received {"code":-32601,"message":"Debugger.setBlackboxPatterns wasn't found"}
2024-11-29 17:33:02.921 [info] Metro 
2024-11-29 17:33:02.922 [info] Metro /Users/pawel/Documents/GitHub/radon-ide/test-apps/expo-51/node_modules/@react-native/dev-middleware/node_modules/ws/lib/websocket.js:329
2024-11-29 17:33:02.922 [info] Metro       const err = new Error(
2024-11-29 17:33:02.922 [info] Metro                   ^
2024-11-29 17:33:02.922 [info] Metro Error: WebSocket is not open: readyState 3 (CLOSED)
2024-11-29 17:33:02.922 [info] Metro     at WebSocket.send (/Users/pawel/Documents/GitHub/radon-ide/test-apps/expo-51/node_modules/@react-native/dev-middleware/node_modules/ws/lib/websocket.js:329:19)
2024-11-29 17:33:02.922 [info] Metro     at WebSocket.socket.send (/Users/pawel/Documents/GitHub/radon-ide/test-apps/expo-51/node_modules/@react-native/dev-middleware/dist/inspector-proxy/Device.js:328:23)
2024-11-29 17:33:02.922 [info] Metro     at /Users/pawel/Documents/GitHub/radon-ide/test-apps/expo-51/node_modules/@react-native/dev-middleware/dist/inspector-proxy/Device.js:504:26
2024-11-29 17:33:02.922 [info] Metro     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-11-29 17:33:02.986 [error] Error: Command failed with exit code 1: node /Users/pawel/.vscode/extensions/swmansion.react-native-ide-1.0.0-rc.1/lib/expo_start.js
	at tj (/Users/pawel/.vscode/extensions/swmansion.react-native-ide-1.0.0-rc.1/dist/extension.js:14:59)
	at /Users/pawel/.vscode/extensions/swmansion.react-native-ide-1.0.0-rc.1/dist/extension.js:14:10506
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5) Metro exited unexpectedly
2024-11-29 17:33:02.986 [error] Error: Command failed with exit code 1: node /Users/pawel/.vscode/extensions/swmansion.react-native-ide-1.0.0-rc.1/lib/expo_start.js
	at tj (/Users/pawel/.vscode/extensions/swmansion.react-native-ide-1.0.0-rc.1/dist/extension.js:14:59)
	at /Users/pawel/.vscode/extensions/swmansion.react-native-ide-1.0.0-rc.1/dist/extension.js:14:10506
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5) Subprocess node /Users/pawel/.vscode/extensions/swmansion.react-native-ide-1.0.0-rc.1/lib/expo_start.js execution resulted in an error:
2024-11-29 17:33:02.986 [error] Error: Metro process exited
	at /Users/pawel/.vscode/extensions/swmansion.react-native-ide-1.0.0-rc.1/dist/extension.js:156:3772
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5) Unhandled promise rejection
```

**Comment by p-malecki** [comment]
Running `npx expo prebuild` resolves this issue.
