### ISSUE TITLE
stuck on booting device using windows mechine

### ISSUE THREAD

**Issue by Maazu897** [software-mansion/radon-ide#812]
I launch the IDE but it Stucks on Booting device for too long . I have tried re launch re installation but stills the same issue.

Environment
I'm using a windows machine.
The Radon IDE version is v0.0.21.
The project is on react native cli and using the VS Code.
Here are the some logs 

2024-12-03 11:55:54.130 [error] Error: ENOENT: no such file or directory, open 'C:\Users\Maaz Ullah\AppDat\Roaming\Code\User\keybindings.json'
    at Object.openSync (node:fs:575:18)
    at Object.func [as openSync] (node:electron/js2c/node_init:2:2559)
    at Object.readFileSync (node:fs:454:35)
    at Object.t.readFileSync (node:electron/js2c/node_init:2:10175)
    at E8.getCommandsCurrentKeyBinding (c:\Users\Maaz Ullah\.vscode\extensions\swmansion.react-native-ide-0.0.21-win32-x64\dist\extension.js:151:3189)
    at _6.handleRemoteCall (c:\Users\Maaz Ullah\.vscode\extensions\swmansion.react-native-ide-0.0.21-win32-x64\dist\extension.js:151:7707)
    at mh.value (c:\Users\Maaz Ullah\.vscode\extensions\swmansion.react-native-ide-0.0.21-win32-x64\dist\extension.js:151:7041)
    at D.B (file:///c:/Users/Maaz%20Ullah/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
    at D.fire (file:///c:/Users/Maaz%20Ullah/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
    at Zj.$onMessage (file:///c:/Users/Maaz%20Ullah/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:90307)
    at py.S (file:///c:/Users/Maaz%20Ullah/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113311)
    at py.Q (file:///c:/Users/Maaz%20Ullah/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113091)
    at py.M (file:///c:/Users/Maaz%20Ullah/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:112180)
    at py.L (file:///c:/Users/Maaz%20Ullah/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:111418)
    at mh.value (file:///c:/Users/Maaz%20Ullah/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:110082)
    at D.B (file:///c:/Users/Maaz%20Ullah/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
    at D.fire (file:///c:/Users/Maaz%20Ullah/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
    at Vn.fire (file:///c:/Users/Maaz%20Ullah/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
    at mh.value (file:///c:/Users/Maaz%20Ullah/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:13300)
    at D.B (file:///c:/Users/Maaz%20Ullah/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
    at D.fire (file:///c:/Users/Maaz%20Ullah/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
    at Vn.fire (file:///c:/Users/Maaz%20Ullah/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
    at MessagePortMain.<anonymous> (file:///c:/Users/Maaz%20Ullah/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11592)
    at MessagePortMain.emit (node:events:519:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949) Error while parsing keybindings.json

**Comment by p-malecki** [comment]
Hello, thank you for reporting. The issue arises because the IDE is unable to locate your vscode's keybindings.json file, which should be found at `%APPDATA%\Code\User\keybindings.json`. If this file does not exist, you can create it by pressing Ctrl+Shift+P and choosing `Preferences: Open Keyboard Shortcuts (JSON)`. Once the file is in place, the IDE should resolve the problem and proceed as expected.

**Comment by Maazu897** [comment]
Got it, but can you  tell me what should be added to the keybindings.Jason file?

**Comment by Maazu897** [comment]
I checked that but got stuck this time there isn't any error; I waited about 30 min but still  is in the booting device phase

**Comment by p-malecki** [comment]
Could you provide the recent logs?

**Comment by Maazu897** [comment]
[error] Error: ENOENT: no such file or directory, open 'C:\Users\Maaz'
    at open (node:internal/fs/promises:641:25)
    at Object.readFile (node:internal/fs/promises:1258:14)
    at A$ (c:\Users\Maaz Ullah\.vscode\extensions\swmansion.react-native-ide-0.0.21-win32-x64\dist\extension.js:146:271)
    at Interface.<anonymous> (c:\Users\Maaz Ullah\.vscode\extensions\swmansion.react-native-ide-0.0.21-win32-x64\dist\extension.js:142:1552) Unhandled promise rejection
2024-12-04 11:33:30.713 [info] 

When the emulator begins booting at the initial stage it shows this error then proceeds with the booting process but gets stuck during the booting phase.

Emulator output INFO    | Ignore IPv6 address: 482f:d888:8c02:0:b007:d888:8c02:0
2024-12-04 11:36:08.554 [info] Emulator output INFO    | Ignore IPv6 address: 482f:d888:8c02:0:b007:d888:8c02:0 (2x)
2024-12-04 11:36:08.554 [info] Emulator output INFO    | Warning: 

These are the last logs; the process is stuck at this point.

**Comment by p-malecki** [comment]
Thank you for providing the logs. Does your username include a space character? I guess that we are currently unable to handle space characters in usernames. Could you try running the IDE from a different user account with a name that doesn't contain any special characters?

**Comment by axtgr** [comment]
> Error: ENOENT: no such file or directory, open 'C:\Users\Maaz Ullah\AppDat\Roaming\Code\User\keybindings.json'

Perhaps the issue here is that the path to the keybindings file contains *AppDat* instead of *AppDat**a***.
