### ISSUE TITLE
Switching localization cause the app to fail to build

### ISSUE THREAD

**Issue by jcgertig** [software-mansion/radon-ide#830]
**Description**
I switched the localization and the app fails to build. I also can not change the localization back

Get this error

2024-12-04 15:59:37.519 [error] Unable to resolve module __RNIDE_lib__/rn-renderer/ReactFabric-dev.js from /Users/jonathan.gertig/work/apps/mobile/node_modules/react-native/Libraries/Renderer/implementations/ReactFabric-dev.js: __RNIDE_lib__/rn-renderer/ReactFabric-dev.js could not be found within the project or in these directories:
  node_modules/react-native/node_modules
  node_modules
  node_modules
  node_modules/react-native/node_modules
  /Users/jonathan.gertig/.vscode/extensions/swmansion.react-native-ide-1.0.0-darwin-arm64/lib/rn-renderer/ReactFabric-dev.js

<img width="391" alt="Screenshot 2024-12-04 at 4 04 24 PM" src="https://github.com/user-attachments/assets/f8180b3b-1699-4b58-b8b3-2de3bde9be49">

**Environment**

- Version of currently used Radon IDE (Extensions tab -> click on Radon IDE extension -> version is located next to the extension name) 1.0.0

**Comment by jcgertig** [comment]
The only way to fix this currently is to uninstall and reinstall the extension

**Comment by filip131311** [comment]
Hello @jcgertig , thank you for providing this issue, for short ter fix you can try to remove the emulator device and add it again, but before you do that mak sure that localization is set to english (you can change it on IOS and then reinstall the device). 

For longer term would you mind providing following information:
1) Radon IDE logs ( you can find them in output section of vscode labeled "Radon IDE"
2) Android emulator logs (can be found in the same section) 
3) check if the problem is android specific ( I do assume so ) 
4) what version of react native do you use, do you use any frameworks, are you working with monorepos, what package manager do you use and is your application part of a monorepo?

**Comment by jcgertig** [comment]
1. 
```
2024-12-04 16:52:27.343 [info] Subprocess xcodebuild -workspace /Users/jonathan.gertig/work/enfusion-web/apps/mobile/ios/Enfusion.xcworkspace -scheme Enfusion -sdk iphonesimulator -configuration Debug -showBuildSettings -json produced error output: 2024-12-04 16:52:27.317 xcodebuild[93280:14643740]  DVTPlugInQuery: Requested but did not find extension point with identifier 'Xcode.InterfaceBuilderBuildSupport.PlatformDefinition'. This is programmer error; code should only request extension points that are defined by itself or its dependencies.
2024-12-04 16:52:27.521 [info] Build completed in 40.50 sec.
2024-12-04 16:52:31.120 [info] Defaults location /Users/jonathan.gertig/Library/Caches/com.swmansion.radon-ide/Devices/iOS/E6923554-B461-4C76-881A-3E68AE2ECF86/data/Containers/Data/Application/A6CE94D0-4FFC-45A9-9811-E62F38ACE046/Library/Preferences/com.enfusion.mobile.plist
2024-12-04 16:52:31.427 [info] Will wait for app ready and for preview
2024-12-04 16:52:31.427 [info] Launch preview /Users/jonathan.gertig/.vscode/extensions/swmansion.react-native-ide-1.0.0-darwin-arm64/dist/simulator-server-macos ios,--id,E6923554-B461-4C76-881A-3E68AE2ECF86,--device-set,/Users/jonathan.gertig/Library/Caches/com.swmansion.radon-ide/Devices/iOS
2024-12-04 16:52:31.892 [info] Stream ready http://127.0.0.1:58364/stream.mjpeg
2024-12-04 16:52:31.892 [info] sim-server: stream_ready http://127.0.0.1:58364/stream.mjpeg
2024-12-04 16:52:31.892 [info] sim-server: [2024-12-04T22:52:31Z INFO  simulator_server::mjpeg_server] MJPEG server started at http://127.0.0.1:58364/stream.mjpeg
2024-12-04 16:52:32.242 [info] Metro {"buildID":"2","bundleDetails":{"bundleType":"bundle","customResolverOptions":{},"customTransformOptions":{},"dev":true,"entryFile":"/Users/jonathan.gertig/work/enfusion-web/apps/mobile/index.js","minify":false,"platform":"ios"},"isPrefetch":false,"type":"bundle_build_started"}
2024-12-04 16:52:44.276 [info] Metro {"buildID":"2","type":"bundle_build_failed","bundleOptions":{"bundleType":"bundle","customResolverOptions":{},"customTransformOptions":{},"dev":true,"entryFile":"./index","excludeSource":false,"hot":true,"inlineSourceMap":false,"lazy":true,"minify":false,"modulesOnly":false,"onProgress":null,"platform":"ios","runModule":true,"shallow":false,"sourceMapUrl":"http://localhost:57572/index.map?platform=ios&dev=true&lazy=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=com.enfusion.mobile","sourcePaths":"absolute","sourceUrl":"http://localhost:57572/index.bundle//&platform=ios&dev=true&lazy=true&minify=false&inlineSourceMap=false&modulesOnly=false&runModule=true&app=com.enfusion.mobile","unstable_transformProfile":"default"}}
2024-12-04 16:52:44.280 [info] Metro {"error":{"originModulePath":"/Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js","targetModuleName":"__RNIDE_lib__/rn-renderer/ReactNativeRenderer-dev.js","message":"Unable to resolve module __RNIDE_lib__/rn-renderer/ReactNativeRenderer-dev.js from /Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js: __RNIDE_lib__/rn-renderer/ReactNativeRenderer-dev.js could not be found within the project or in these directories:\n  node_modules/react-native/node_modules\n  node_modules\n  node_modules\n  node_modules/react-native/node_modules\n  /Users/jonathan.gertig/.vscode/extensions/swmansion.react-native-ide-1.0.0-darwin-arm64/lib/rn-renderer/ReactNativeRenderer-dev.js\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 1 |\u001b[39m \u001b[90m/**\u001b[39m\n \u001b[90m   |\u001b[39m              \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 2 |\u001b[39m \u001b[90m * Copyright (c) Meta Platforms, Inc. and affiliates.\u001b[39m\n \u001b[90m 3 |\u001b[39m \u001b[90m *\u001b[39m\n \u001b[90m 4 |\u001b[39m \u001b[90m * This source code is licensed under the MIT license found in the\u001b[39m\u001b[0m","cause":{"dirPaths":["/Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules/react-native/Libraries/Renderer/implementations/node_modules","/Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules/react-native/Libraries/Renderer/node_modules","/Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules/react-native/Libraries/node_modules","/Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules/react-native/node_modules","/Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules/node_modules","/Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules","/Users/jonathan.gertig/work/enfusion-web/apps/node_modules","/Users/jonathan.gertig/work/enfusion-web/node_modules","/Users/jonathan.gertig/work/node_modules","/Users/jonathan.gertig/node_modules","/Users/node_modules","/node_modules","/Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules","/Users/jonathan.gertig/work/enfusion-web/apps/node_modules","/Users/jonathan.gertig/work/enfusion-web/node_modules","/Users/jonathan.gertig/work/node_modules","/Users/jonathan.gertig/node_modules","/Users/node_modules","/Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules/react-native/node_modules"],"extraPaths":["/Users/jonathan.gertig/.vscode/extensions/swmansion.react-native-ide-1.0.0-darwin-arm64/lib/rn-renderer/ReactNativeRenderer-dev.js"]},"errors":[{"description":"Unable to resolve module __RNIDE_lib__/rn-renderer/ReactNativeRenderer-dev.js from /Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js: __RNIDE_lib__/rn-renderer/ReactNativeRenderer-dev.js could not be found within the project or in these directories:\n  node_modules/react-native/node_modules\n  node_modules\n  node_modules\n  node_modules/react-native/node_modules\n  /Users/jonathan.gertig/.vscode/extensions/swmansion.react-native-ide-1.0.0-darwin-arm64/lib/rn-renderer/ReactNativeRenderer-dev.js\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 1 |\u001b[39m \u001b[90m/**\u001b[39m\n \u001b[90m   |\u001b[39m              \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 2 |\u001b[39m \u001b[90m * Copyright (c) Meta Platforms, Inc. and affiliates.\u001b[39m\n \u001b[90m 3 |\u001b[39m \u001b[90m *\u001b[39m\n \u001b[90m 4 |\u001b[39m \u001b[90m * This source code is licensed under the MIT license found in the\u001b[39m\u001b[0m"}]},"type":"bundling_error","message":"Unable to resolve module __RNIDE_lib__/rn-renderer/ReactNativeRenderer-dev.js from /Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js: __RNIDE_lib__/rn-renderer/ReactNativeRenderer-dev.js could not be found within the project or in these directories:\n  node_modules/react-native/node_modules\n  node_modules\n  node_modules\n  node_modules/react-native/node_modules\n  /Users/jonathan.gertig/.vscode/extensions/swmansion.react-native-ide-1.0.0-darwin-arm64/lib/rn-renderer/ReactNativeRenderer-dev.js\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 1 |\u001b[39m \u001b[90m/**\u001b[39m\n \u001b[90m   |\u001b[39m              \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 2 |\u001b[39m \u001b[90m * Copyright (c) Meta Platforms, Inc. and affiliates.\u001b[39m\n \u001b[90m 3 |\u001b[39m \u001b[90m *\u001b[39m\n \u001b[90m 4 |\u001b[39m \u001b[90m * This source code is licensed under the MIT license found in the\u001b[39m\u001b[0m","stack":"Error: Unable to resolve module __RNIDE_lib__/rn-renderer/ReactNativeRenderer-dev.js from /Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js: __RNIDE_lib__/rn-renderer/ReactNativeRenderer-dev.js could not be found within the project or in these directories:\n  node_modules/react-native/node_modules\n  node_modules\n  node_modules\n  node_modules/react-native/node_modules\n  /Users/jonathan.gertig/.vscode/extensions/swmansion.react-native-ide-1.0.0-darwin-arm64/lib/rn-renderer/ReactNativeRenderer-dev.js\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 1 |\u001b[39m \u001b[90m/**\u001b[39m\n \u001b[90m   |\u001b[39m              \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 2 |\u001b[39m \u001b[90m * Copyright (c) Meta Platforms, Inc. and affiliates.\u001b[39m\n \u001b[90m 3 |\u001b[39m \u001b[90m *\u001b[39m\n \u001b[90m 4 |\u001b[39m \u001b[90m * This source code is licensed under the MIT license found in the\u001b[39m\u001b[0m\n    at ModuleResolver.resolveDependency (/Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:139:15)\n    at DependencyGraph.resolveDependency (/Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules/metro/src/node-haste/DependencyGraph.js:232:43)\n    at /Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules/metro/src/lib/transformHelpers.js:156:21\n    at resolveDependencies (/Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules/metro/src/DeltaBundler/buildSubgraph.js:42:25)\n    at visit (/Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules/metro/src/DeltaBundler/buildSubgraph.js:83:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Promise.all (index 0)\n    at async visit (/Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)\n    at async Promise.all (index 35)\n    at async visit (/Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)"}
2024-12-04 16:52:44.280 [error] Unable to resolve module __RNIDE_lib__/rn-renderer/ReactNativeRenderer-dev.js from /Users/jonathan.gertig/work/enfusion-web/apps/mobile/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js: __RNIDE_lib__/rn-renderer/ReactNativeRenderer-dev.js could not be found within the project or in these directories:
  node_modules/react-native/node_modules
  node_modules
  node_modules
  node_modules/react-native/node_modules
  /Users/jonathan.gertig/.vscode/extensions/swmansion.react-native-ide-1.0.0-darwin-arm64/lib/rn-renderer/ReactNativeRenderer-dev.js
> 1 | /**
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 |  * Copyright (c) Meta Platforms, Inc. and affiliates.
  3 |  *
  4 |  * This source code is licensed under the MIT license found in the
  ```
  
 2. This is ios simulator as in the screenshot
 3. Its both ios and android
 4. RN 0.75.3, it is a monorepo #821
<img width="499" alt="Screenshot 2024-12-04 at 4 54 54 PM" src="https://github.com/user-attachments/assets/11cbc391-f186-4069-b808-c26a00c827ba">

**Comment by jcgertig** [comment]
@filip131311 an ideas?

**Comment by aymather** [comment]
If you close the Radon IDE window completely, stop yarn, start with `yarn cache clean && yarn start --reset-cache`, then reopen Radon IDE, the error goes away.

But this is a very cumbersome solution :/
