### ISSUE TITLE
Stuck in Booting Device...

### ISSUE THREAD

**Issue by piyush362** [software-mansion/radon-ide#836]
**Description**

**Environment**

- Version of currently used Radon IDE (Extensions tab -> click on Radon IDE extension -> version is located next to the extension name)
- Version of React Native/Expo used in the project.
- Any other versions of tools related to the problem.

![image](https://github.com/user-attachments/assets/1798a117-7f18-4f0e-8942-5a2fd034bc3d)

I am stuck in booting device screen...

**Comment by p-malecki** [comment]
Thank you for reporting. Could you please attach the logs from Radon IDE along with the environment information?

**Comment by vonkanehoffen** [comment]
I'm getting this issue too. See log below. Any ideas?

Radon Version: v1.0.0
RN/Expo: "0.74.5" / "~51.0.39"
Cursor

```
2024-12-10 21:43:55.299 [warning] Found multiple **/node_modules/react-native/package.json files in the workspace
2024-12-10 21:43:55.423 [info] Found app root folder: /Users/kane/Code/gh-repos/mobilityways/Mobilityways-2/Mobilityways.MobileApp
2024-12-10 21:43:57.835 [info] Launching devtools
2024-12-10 21:43:57.835 [info] Launching metro
2024-12-10 21:43:57.847 [info] Devtools started on port 58556
2024-12-10 21:43:58.153 [info] Device selected Google Pixel 9
2024-12-10 21:43:58.153 [info] Selected device is ready
2024-12-10 21:43:58.255 [info] Found Xcode workspace /Users/kane/Code/gh-repos/mobilityways/Mobilityways-2/Mobilityways.MobileApp/ios/Mobilityways.xcworkspace
2024-12-10 21:44:00.085 [error] CodeExpectedError: cannot open file:///Users/kane/Code/gh-repos/mobilityways/Mobilityways-2/Mobilityways.MobileApp/assets/images/splash-icon.png. Detail: File seems to be binary and cannot be opened as text
    at p.$tryOpenDocument (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3119:133017) Unhandled promise rejection
2024-12-10 21:44:00.092 [error] CodeExpectedError: cannot open file:///Users/kane/Code/gh-repos/mobilityways/Mobilityways-2/Mobilityways.MobileApp/assets/images/liftshare-car%403x.png. Detail: File seems to be binary and cannot be opened as text
    at p.$tryOpenDocument (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3119:133017) Unhandled promise rejection
2024-12-10 21:44:00.317 [error] CodeExpectedError: cannot open file:///Users/kane/Code/gh-repos/mobilityways/Mobilityways-2/Mobilityways.MobileApp/assets/images/splash-icon.png. Detail: File seems to be binary and cannot be opened as text
    at p.$tryOpenDocument (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3119:133017) Unhandled promise rejection
2024-12-10 21:44:00.317 [error] CodeExpectedError: cannot open file:///Users/kane/Code/gh-repos/mobilityways/Mobilityways-2/Mobilityways.MobileApp/assets/images/liftshare-car%403x.png. Detail: File seems to be binary and cannot be opened as text
    at p.$tryOpenDocument (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3119:133017) Unhandled promise rejection
2024-12-10 21:44:00.373 [error] CodeExpectedError: cannot open file:///Users/kane/Code/gh-repos/mobilityways/Mobilityways-2/Mobilityways.MobileApp/assets/images/liftshare-car%403x.png. Detail: File seems to be binary and cannot be opened as text
    at p.$tryOpenDocument (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3119:133017) Unhandled promise rejection
2024-12-10 21:44:00.373 [error] CodeExpectedError: cannot open file:///Users/kane/Code/gh-repos/mobilityways/Mobilityways-2/Mobilityways.MobileApp/assets/images/splash-icon.png. Detail: File seems to be binary and cannot be opened as text
    at p.$tryOpenDocument (vscode-file://vscode-app/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3119:133017) Unhandled promise rejection
2024-12-10 21:44:03.338 [info] Node modules already installed - skipping
2024-12-10 21:44:03.726 [info] Metro Starting project at /Users/kane/Code/gh-repos/mobilityways/Mobilityways-2/Mobilityways.MobileApp
2024-12-10 21:44:03.731 [info] Metro env: load .env.local
2024-12-10 21:44:03.731 [info] Metro env: export EXPO_PUBLIC_API_URL
2024-12-10 21:44:04.542 [info] Metro {"type":"RNIDE_watch_folders","watchFolders":["/Users/kane/Code/gh-repos/mobilityways/Mobilityways-2/Mobilityways.MobileApp","/Users/kane/Code/gh-repos/mobilityways/Mobilityways-2/Mobilityways.MobileApp","/Users/kane/.cursor/extensions/swmansion.react-native-ide-1.0.0-darwin-arm64/lib"]}
2024-12-10 21:44:04.542 [info] Captured metro watch folders ["/Users/kane/Code/gh-repos/mobilityways/Mobilityways-2/Mobilityways.MobileApp","/Users/kane/Code/gh-repos/mobilityways/Mobilityways-2/Mobilityways.MobileApp","/Users/kane/.cursor/extensions/swmansion.react-native-ide-1.0.0-darwin-arm64/lib"]
2024-12-10 21:44:05.712 [info] Metro {"hasReducedPerformance":false,"port":0,"type":"initialize_started"}
2024-12-10 21:44:05.712 [info] Metro {"type":"dep_graph_loading","hasReducedPerformance":false}
2024-12-10 21:44:05.760 [info] Metro {"type":"RNIDE_initialize_done","port":58616}
2024-12-10 21:44:05.760 [info] Metro started on port 58616
2024-12-10 21:44:05.761 [info] Metro & devtools ready
2024-12-10 21:44:05.855 [info] Emulator output INFO    | Storing crashdata in: /tmp/android-kane/emu-crash-35.1.20.db, detection is enabled for process: 33977
2024-12-10 21:44:05.855 [info] Emulator output INFO    | Android emulator version 35.1.20.0 (build_id 12234392) (CL:N/A)
2024-12-10 21:44:05.855 [info] Emulator output INFO    | Graphics backend: gfxstream
2024-12-10 21:44:05.855 [info] Emulator output INFO    | Found systemPath /Users/kane/Library/Android/sdk/system-images/android-35/google_apis_playstore/arm64-v8a
2024-12-10 21:44:06.164 [info] Emulator output WARNING | System image is writable
2024-12-10 21:44:06.164 [info] Emulator output INFO    | Storing crashdata in: /tmp/android-kane/emu-crash-35.1.20.db, detection is enabled for process: 33977
2024-12-10 21:44:06.164 [info] Emulator output INFO    | Duplicate loglines will be removed, if you wish to see each individual line launch with the -log-nofilter flag.
2024-12-10 21:44:06.164 [info] Emulator output INFO    | Increasing RAM size to 2048MB
2024-12-10 21:44:06.279 [info] Emulator output INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_new_posture_requested(int) ((null):0, (null))
2024-12-10 21:44:06.279 [info] Emulator output INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_dismiss_posture_selection_dialog() ((null):0, (null))
2024-12-10 21:44:06.279 [info] Emulator output INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_new_resizable_requested(PresetEmulatorSizeType) ((null):0, (null))
2024-12-10 21:44:06.279 [info] Emulator output INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_dismiss_resizable_dialog() ((null):0, (null))
2024-12-10 21:44:06.279 [info] Emulator output INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_sleep_timer_done() ((null):0, (null))
2024-12-10 21:44:06.279 [info] Emulator output INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_unfold_timer_done() ((null):0, (null))
2024-12-10 21:44:06.313 [info] Emulator output library_mode host gpu mode host
2024-12-10 21:44:06.313 [info] Emulator output INFO    | Initializing hardware OpenGLES emulation support
2024-12-10 21:44:06.433 [info] Emulator output android_startOpenglesRenderer: gpu infoI1210 21:44:06.433304 07d7840 HealthMonitor.cpp:279] HealthMonitor disabled.
2024-12-10 21:44:06.433 [info] Emulator output I1210 21:44:06.433355 07d7840 VulkanDispatch.cpp:74] initIcdPaths: ICD set to 'swiftshader', using Swiftshader ICD
2024-12-10 21:44:06.433 [info] Emulator output I1210 21:44:06.433380 07d7840 VulkanDispatch.cpp:43] Setting ICD filenames for the loader = /Users/kane/Library/Android/sdk/emulator/qemu/darwin-aarch64/lib64/vulkan/vk_swiftshader_icd.json:/Users/kane/Library/Android/sdk/emulator/lib64/vulkan/vk_swiftshader_icd.json
2024-12-10 21:44:06.433 [info] Emulator output cannot add library /Users/kane/Library/Android/sdk/emulator/qemu/darwin-aarch64/lib64/vulkan/libvulkan.dylib: failed
2024-12-10 21:44:06.434 [info] Emulator output added library /Users/kane/Library/Android/sdk/emulator/lib64/vulkan/libvulkan.dylib
2024-12-10 21:44:06.441 [info] Emulator output W1210 21:44:06.441604 07d7840 VkCommonOperations.cpp:1022] Selecting Vulkan device: SwiftShader Device (LLVM 10.0.0), Version: 1.2.0
2024-12-10 21:44:06.449 [info] Emulator output initialize: Supports id properties, got a vulkan device UUID
2024-12-10 21:44:06.480 [info] Emulator output I1210 21:44:06.479870 07d7840 VkCommonOperations.cpp:1361] Initializing VkEmulation features:
2024-12-10 21:44:06.480 [info] Emulator output I1210 21:44:06.479883 07d7840 VkCommonOperations.cpp:1362]     glInteropSupported: false
2024-12-10 21:44:06.480 [info] Emulator output I1210 21:44:06.479885 07d7840 VkCommonOperations.cpp:1363]     useDeferredCommands: true
2024-12-10 21:44:06.480 [info] Emulator output I1210 21:44:06.479886 07d7840 VkCommonOperations.cpp:1365]     createResourceWithRequirements: true
2024-12-10 21:44:06.480 [info] Emulator output I1210 21:44:06.479888 07d7840 VkCommonOperations.cpp:1366]     useVulkanComposition: false
2024-12-10 21:44:06.480 [info] Emulator output I1210 21:44:06.479889 07d7840 VkCommonOperations.cpp:1367]     useVulkanNativeSwapchain: false
2024-12-10 21:44:06.480 [info] Emulator output I1210 21:44:06.479890 07d7840 VkCommonOperations.cpp:1368]     enable guestRenderDoc: false
2024-12-10 21:44:06.480 [info] Emulator output I1210 21:44:06.479892 07d7840 VkCommonOperations.cpp:1369]     ASTC LDR emulation mode: 2
2024-12-10 21:44:06.480 [info] Emulator output I1210 21:44:06.479893 07d7840 VkCommonOperations.cpp:1370]     enable ETC2 emulation: true
2024-12-10 21:44:06.480 [info] Emulator output I1210 21:44:06.479894 07d7840 VkCommonOperations.cpp:1371]     enable Ycbcr emulation: false
2024-12-10 21:44:06.480 [info] Emulator output I1210 21:44:06.479895 07d7840 VkCommonOperations.cpp:1372]     guestVulkanOnly: false
2024-12-10 21:44:06.480 [info] Emulator output I1210 21:44:06.479896 07d7840 VkCommonOperations.cpp:1373]     useDedicatedAllocations: false
2024-12-10 21:44:06.480 [info] Emulator output I1210 21:44:06.480134 07d7840 FrameBuffer.cpp:505] Graphics Adapter Vendor Google (Apple)
2024-12-10 21:44:06.480 [info] Emulator output I1210 21:44:06.480139 07d7840 FrameBuffer.cpp:506] Graphics Adapter Android Emulator OpenGL ES Translator (Apple M3 Pro)
2024-12-10 21:44:06.480 [info] Emulator output I1210 21:44:06.480141 07d7840 FrameBuffer.cpp:507] Graphics API Version OpenGL ES 3.0 (4.1 Metal - 89.3)
2024-12-10 21:44:06.480 [info] Emulator output I1210 21:44:06.480143 07d7840 FrameBuffer.cpp:508] Graphics API Extensions GL_OES_EGL_sync GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_depth24 GL_OES_depth32 GL_OES_element_index_uint GL_OES_texture_float GL_OES_texture_float_linear GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_texture GL_OES_texture_npot GL_OES_rgb8_rgba8 GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_texture_format_BGRA8888 GL_APPLE_texture_format_BGRA8888 
2024-12-10 21:44:06.480 [info] Emulator output I1210 21:44:06.480145 07d7840 FrameBuffer.cpp:509] Graphics Device Extensions N/A
2024-12-10 21:44:06.481 [info] Emulator output INFO    | Sending adb public key [Qxxxxxxxx= kane@unknown]
2024-12-10 21:44:06.641 [info] Emulator output INFO    | Monitoring duration of emulator setup.
2024-12-10 21:44:06.643 [info] Emulator output INFO    | Using security allow list from: /Users/kane/Library/Android/sdk/emulator/lib/emulator_access.json
2024-12-10 21:44:06.643 [info] Emulator output WARNING | *** Basic token auth should only be used by android-studio ***
2024-12-10 21:44:06.644 [info] Emulator output INFO    | The active JSON Web Key Sets can be found here: /Users/kane/Library/Caches/TemporaryItems/avd/running/33977/jwks/5a9a4724-ed2d-4b93-bb7b-9bf6bc817c07/active.jwk
2024-12-10 21:44:06.644 [info] Emulator output INFO    | Scanning /Users/kane/Library/Caches/TemporaryItems/avd/running/33977/jwks/5a9a4724-ed2d-4b93-bb7b-9bf6bc817c07 for jwk keys.
2024-12-10 21:44:06.645 [info] Emulator output INFO    | Started GRPC server at 127.0.0.1:8554, security: Local, auth: +token
2024-12-10 21:44:06.646 [info] Emulator output INFO    | Advertising in: /Users/kane/Library/Caches/TemporaryItems/avd/running/pid_33977.ini
2024-12-10 21:44:06.647 [info] Parsing ini file /Users/kane/Library/Caches/TemporaryItems/avd/running/pid_33977.ini
2024-12-10 21:44:06.655 [info] Emulator output I1210 21:44:06.655057 eef3000 FrameBuffer.cpp:2884] Setting display: 0 configuration to: 1080x2400, dpi: 420x420 
2024-12-10 21:44:06.655 [info] Emulator output I1210 21:44:06.655075 eef3000 FrameBuffer.cpp:2897] setDisplayActiveConfig 0
2024-12-10 21:44:06.802 [info] Emulator output INFO    | Loading snapshot 'default_boot'...
2024-12-10 21:44:06.802 [info] Emulator output WARNING | Device 'vendor' does not have the requested snapshot 'default_boot'
2024-12-10 21:44:06.802 [info] Emulator output WARNING | Failed to load snapshot 'default_boot'
2024-12-10 21:44:06.802 [info] Emulator output INFO    | OpenGL Vendor=[Google (Apple)]
2024-12-10 21:44:06.802 [info] Emulator output INFO    | OpenGL Renderer=[Android Emulator OpenGL ES Translator (Apple M3 Pro)]
2024-12-10 21:44:06.802 [info] Emulator output INFO    | OpenGL Version=[OpenGL ES 3.0 (4.1 Metal - 89.3)]
2024-12-10 21:44:06.872 [info] Metro Waiting on http://localhost:8081
2024-12-10 21:44:06.872 [info] Metro Logs for your project will appear below.
2024-12-10 21:44:06.925 [info] Emulator output 2024-12-10 21:44:06.925 qemu-system-aarch64[33977:5958531] +[IMKClient subclass]: chose IMKClient_Modern
2024-12-10 21:44:06.925 [info] Emulator output 2024-12-10 21:44:06.925 qemu-system-aarch64[33977:5958531] +[IMKInputSession subclass]: chose IMKInputSession_Modern
2024-12-10 21:44:07.638 [info] Emulator output INFO    | Activated packet streamer for bluetooth emulation
2024-12-10 21:44:12.011 [info] Metro {"type":"dep_graph_loaded"}
2024-12-10 21:44:12.011 [info] Metro {"type":"transformer_load_started"}
2024-12-10 21:44:12.133 [info] Metro {"type":"transformer_load_done"}
2024-12-10 21:44:12.133 [info] Metro {"type":"initialize_done","port":0}
2024-12-10 21:44:14.635 [info] Calculating fingerprint
2024-12-10 21:44:15.677 [info] Emulator output INFO    | Boot completed in 9760 ms
2024-12-10 21:44:15.677 [info] Emulator output INFO    | Increasing screen off timeout, logcat buffer size to 2M.
2024-12-10 21:44:22.498 [info] App folder fingerprint fd72d1ddc3880ed1ec6196f4d2915e2675c6134c
```

**Comment by kmagiera** [comment]
@vonkanehoffen does it get stuck on booting in your case as well? Can you sucesfully boot an iOS device?

**Comment by vonkanehoffen** [comment]
@kmagiera yeah it gets stuck. iOS works fine

**Comment by kmagiera** [comment]
Can you try creating a new device on Android, perhaps with a different system image?

**Comment by janwiebe-jump** [comment]
I have the same issue with a brand new Pixel 9 emulator created by Radon IDE
